services:
  redis:
    image: "redis:alpine"
  postgres:
    image: "postgres:15"
    environment:
      POSTGRES_USER: JustDjango
      POSTGRES_PASSWORD: JustDjango
      POSTGRES_DB: JustDjangoDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
  celery:
    build: .
    command: celery -A JustDjango.celery_app worker --loglevel=info
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: