# Generated by Django 5.2 on 2025-05-03 15:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fabric', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID відгуку')),
                ('category', models.CharField(choices=[('general', 'Загальний'), ('product', 'Продукт'), ('service', 'Сервіс'), ('other', 'Інше')], default='general', max_length=20, verbose_name='Категорія відгуку')),
                ('status', models.CharField(choices=[('new', 'Новий'), ('in_progress', 'В обробці'), ('resolved', 'Вирішено'), ('closed', 'Закрито')], default='new', max_length=20, verbose_name='Статус обробки')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Оцінка від 1 до 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оцінка')),
                ('comment', models.TextField(help_text='Текст відгуку', verbose_name='Коментар')),
                ('language', models.CharField(default='uk', help_text='Код мови тексту відгуку', max_length=10, verbose_name='Мова відгуку')),
                ('manager_response', models.TextField(blank=True, help_text='Текст відповіді менеджера на відгук', verbose_name='Відповідь менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('product', models.ForeignKey(blank=True, help_text='Прив’язати відгук до конкретного продукту', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='fabric.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(blank=True, help_text='Авторизований користувач, що залишив відгук', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='feedback_fe_created_84c297_idx'), models.Index(fields=['status'], name='feedback_fe_status_35d074_idx'), models.Index(fields=['category'], name='feedback_fe_categor_9a32a3_idx')],
            },
        ),
    ]
